apiVersion: v1
kind: Secret
metadata:
  name: scopbot-secrets   # âœ… renamed for clarity
  namespace: scopbot
type: Opaque
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: MTQ0MA==
  ALGORITHM: SFMyNTY=
  APP_ENV: ZGV2ZWxvcG1lbnQ=
  APP_NAME: QUktUG93ZXJlZCBQcm9qZWN0IFNjb3BpbmcgQm90
  APP_PORT: ODAwMA==
  APPINSIGHTS_INSTRUMENTATION_KEY: eW91ci1hcHBpbnNpZ2h0cy1rZXk=
  AZURE_OPENAI_DEPLOYMENT: Z3B0LTRv
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT: dGV4dC1lbWJlZGRpbmctMy1sYXJnZQ==
  AZURE_OPENAI_ENDPOINT: aHR0cHM6Ly9vbXByYXNhZG9wZW5haS5vcGVuYWkuYXp1cmUuY29tLw==
  AZURE_OPENAI_KEY: ZExXY2EyZDZ2eElMNzdQYkJMVUJHN1ltc0hBWVA1SWdYeElyTWNDTVBENWJQTWs3eTBSZEpRUUo5OUJJQUNZZUJqRlhKM3czQUFBQkFDT0d1MzQ0
  AZURE_OPENAI_VERSION: MjAyNC0xMS0yMA==
  AZURE_SEARCH_ENDPOINT: aHR0cHM6Ly9zY29wYm90YWlzZWFyY2guc2VhcmNoLndpbmRvd3MubmV0
  AZURE_SEARCH_INDEX: cmFnLTE3NTg3NDY4MjE4MDY=
  AZURE_SEARCH_KEY: STF4eUF0RE1RYWFIeEJrYjF3bXhHOHBMQmlySzl4dUFuZ2N6V1AzenNsQXpTZUI1NEJLbw==
  AZURE_STORAGE_ACCOUNT: cHJvamVjdHNjb3Bpbmdib3Q=
  AZURE_STORAGE_CONTAINER: c2NvcGluZ2JvdA==
  AZURE_STORAGE_KEY: RmRnSmtFZlBOMENndWpDY1pxdFpVdWNMKzIzVkFKQ0plcnRTVjNlUXBPb09UbUF4UXBONFNkL3Axc1pTaFZUb1dpR2lWWGRjcjJkRytBU3R2endzaFE9PQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOm9tcHJhc2FkMTIzQGRhdGFiYXNlLTIuYzJkcXVzOGVhbXhzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Nob3BwaW5n
  FRONTEND_URL: aHR0cDovL2xvY2FsaG9zdDo1MTcz
  JIRA_PROJECT_KEY: U0NPUEVS
  JIRA_TOKEN: eW91ci1qaXJhLWFwaS10b2tlbg==
  JIRA_URL: aHR0cHM6Ly95b3VyY29tcGFueS5hdGxhc3NpYW4ubmV0
  JIRA_USER: eW91ci1qaXJhLWVtYWls
  REFRESH_TOKEN_EXPIRE_DAYS: Nw==
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtdGhpcw==
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PASS: bHJ6cmF1bHZza2tvaWVidw==
  SMTP_PORT: NTg3
  SMTP_USER: b21wcmFzYWRrYWRlQGdtYWlsLmNvbQ==
  UPLOAD_DIR: dXBsb2Fkcw==
