apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scopbot-frontend.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Proxy API requests internally to backend
        location /api/ {
            proxy_pass http://{{ .Values.backendService.name }}:{{ .Values.backendService.port }}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Serve SPA React routes
        location / {
            try_files $uri /index.html;
        }
    }
