apiVersion: v1
kind: Service
metadata:
  name: {{ include "scopbot-frontend.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "scopbot-frontend.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "scopbot-frontend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
