replicaCount: 1

image:
  repository: omprasadkade/scopbot-frontend
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer     
  port: 80               

backendService:
  name: scopbot-backend-svc
  port: 8000              

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

namespace: scopbot

ingress:
  enabled: false
