replicaCount: 2

image:
  repository: omprasadkade/scopbot-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

backendService:
  name: scopbot-backend-svc
  port: 8000

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

namespace: scopbot

ingress:
  enabled: true
  className: nginx
  host: scopbot.cloudapp.azure.com
  tlsEnabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - scopbot.eastus.cloudapp.azure.com
      secretName: scopbot-tls
