replicaCount: 1

image:
  repository: omprasadkade/scopbot-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP     # internal only (Ingress will expose)
  port: 80

backendService:
  name: scopbot-backend-svc
  port: 8000

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

namespace: scopbot

ingress:
  enabled: true
  className: nginx
  host: ""               # optional — can be blank for IP-based access
  tlsEnabled: false      # ❌ no TLS
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Accept"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Disposition"
