replicaCount: 2

image:
  repository: omprasadkade/scopbot-backend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

envSecretName: scopbot-secrets
namespace: scopbot

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

command:
  - "uvicorn"
args:
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"
  - "--limit-max-requests"
  - "500000000"
