replicaCount: 2

image:
  repository: omprasadkade/scopbot-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

envSecretName: scopbot-secrets
namespace: scopbot

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

command:
  - "uvicorn"
args:
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"
  - "--limit-max-requests"
  - "500000000"
keyvault:
  name: kv-scopebot
  tenantId: 4ac50105-0c66-404e-a107-7cbd8a9a6442
  clientId: f0762b13-92cb-44e1-be77-ee412fc9f172
