apiVersion: v1
kind: Secret
metadata:
  name: scopbot-secrets 
  namespace: scopbot
type: Opaque
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: MTQ0MA==
  ALGORITHM: SFMyNTY=
  
  AZURE_OPENAI_DEPLOYMENT: Z3B0LTRv
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT: dGV4dC1lbWJlZGRpbmctMy1sYXJnZQ==
  AZURE_OPENAI_ENDPOINT: aHR0cHM6Ly9vbXByYXNhZG9wZW5haS5vcGVuYWkuYXp1cmUuY29tLw==
  AZURE_OPENAI_KEY: ZExXY2EyZDZ2eElMNzdQYkJMVUJHN1ltc0hBWVA1SWdYeElyTWNDTVBENWJQTWs3eTBSZEpRUUo5OUJJQUNZZUJqRlhKM3czQUFBQkFDT0d1MzQ0
  AZURE_OPENAI_VERSION: MjAyNC0xMS0yMA==

  AZURE_SEARCH_ENDPOINT: aHR0cHM6Ly9zY29wYm90YWlzZWFyY2guc2VhcmNoLndpbmRvd3MubmV0
  AZURE_SEARCH_INDEX: cmFnLTE3NTg3NDY4MjE4MDY=
  AZURE_SEARCH_KEY: STF4eUF0RE1RYWFIeEJrYjF3bXhHOHBMQmlySzl4dUFuZ2N6V1AzenNsQXpTZUI1NEJLbw==
  AZURE_STORAGE_ACCOUNT: cHJvamVjdHNjb3Bpbmdib3Q=
  AZURE_STORAGE_CONTAINER: c2NvcGluZ2JvdA==

  AZURE_STORAGE_KEY: RmRnSmtFZlBOMENndWpDY1pxdFpVdWNMKzIzVkFKQ0plcnRTVjNlUXBPb09UbUF4UXBONFNkL3Axc1pTaFZUb1dpR2lWWGRjcjJkRytBU3R2endzaFE9PQ==
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vU2lnbW9pZDpQb3N0Z3JlMTIzQHRlY2hkZW1vLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbTo1NDMyL3Njb3Bib3RkZXY=
  FRONTEND_URL: aHR0cDovLzQ4LjIxNi4xMzIuNzI=
  
  REFRESH_TOKEN_EXPIRE_DAYS: Nw==
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtdGhpcw==

  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PASS: bHJ6cmF1bHZza2tvaWVidw==
  SMTP_PORT: NTg3
  SMTP_USER: b21wcmFzYWRrYWRlQGdtYWlsLmNvbQ==
